
# TODO varnish config on this host

#sub vcl_fetch {
#        unset beresp.http.x-powered-by;
#        set beresp.grace = 24h;

    director_backends = []
    backends = []

    run("""

mkdir -pv /etc/varnish

""")

    cuisine.package_ensure("varnish")

    run("""

test -f /etc/varnish/default.vcl.DISTRIBUTION || \
    cp /etc/varnish/default.vcl /etc/varnish/default.vcl.DISTRIBUTION

""")

    for server in sorted(metadata.servers):
        if 'applications' in metadata.servers[server]:
            for application in sorted(metadata.servers[server]['applications']):
                for container in sorted(metadata.servers[server]['applications'][application]):
                    container_ip = metadata.servers[server]['applications'][application][container]['ip']

                    if metadata.config["debug"] == True:
                        puts(red("adding varnish backend %s/%s/%s (%s)" % (server, application, container, container_ip)))

                    director_backends.append("""    {
        .backend = %s_%s_%s;
        .weight = 10;
    }
""" % (server, application, container))

                    #
                    # build the backends array
                    #
                    backends.append("""backend %s_%s_%s {
    .host                  = "%s";
    .port                  = "80";
    .connect_timeout       = 5s;
    .first_byte_timeout    = 30s;
    .between_bytes_timeout = 30s;
    .max_connections       = 100;
    .saintmode_threshold   = 100;

    .probe = {
                .url       = "/status.php";
                .interval  = 10s;
                .timeout   = 10s;
                .window    = 5;
                .threshold = 3;
    }
}
""" % (
        server,
        application,
        container,
        container_ip
    ))

                #
                # build the director and the backends
                #
                director = """
director %s_%s random {
%s
} """ % (env.host_string, application, "\n".join(director_backends))

                if metadata.config["debug"] == True:
                    puts(red("adding director: %s" % director))

    cuisine.file_write("/etc/varnish/default.vcl", """
#
# this file has been autogenerated
#

""")

    cuisine.file_append("/etc/varnish/default.vcl", "\n".join(backends))

    cuisine.file_append("/etc/varnish/default.vcl", director)

    #
    # https://www.varnish-cache.org/trac/wiki/VCLExampleDirector
    #
    cuisine.file_append("/etc/varnish/default.vcl", """

#
# use the application director for all incoming traffic
#

sub vcl_recv {
    set req.backend = %s_%s;
}
""" % (env.host_string, application))

    run("""

service varnish restart

ps axufww | grep -v grep | grep varnish

""")

