
TMPDIR = $(PWD)/tmp

AUTOGENERATED = $(PWD)/autogenerated

ifeq "" "$(CONFIGFILE)"
CONFIGFILE = $(PWD)/conf/servers.yaml
endif

ifeq "" "$(NODEPS)"
PREREQUISITES = autogenerated preflight sshconfig
endif

STAGES = $(AUTOGENERATED)

INCLUDE = include

REQUIREMENTS = $(INCLUDE)/requirements.txt

PP = PYTHONPATH="$(PWD)/lib"

CC = CONFIGFILE="$(CONFIGFILE)"

DD = DEBUG="$(DEBUG)"

TT = TMPDIR="$(TMPDIR)"

SSHCONFIG = $(TMPDIR)/.ssh/config

FABSSH = --ssh-config-path=$(SSHCONFIG) --disable-known-hosts

FABFILE = --fabfile $(STAGES)/$(@)/fabfile.py

FAB = $(DD) $(PP) $(CC) $(TT) fab $(FABSSH) $(FABFILE) $(@)

RUNSTAGE = $(FAB)

preflight: pipinstalled pipdeps $(TMPDIR)

$(TMPDIR):
	mkdir -pv $(TMPDIR)

autogenerated:
	stages/$(@)/bin/$(@).sh

pipinstalled:
	which pip || sudo apt-get -y install python-pip
	dpkg -l | grep ^ii | grep python-dev || sudo apt-get -y install python-dev
	dpkg -l | grep ^ii | grep python-yaml || sudo apt-get -y install python-yaml
	dpkg -l | grep ^ii | grep python-netaddr || sudo apt-get -y install python-netaddr

pipdeps:
	pip list | grep -i Fabric || sudo pip install --upgrade -r "$(REQUIREMENTS)"

#
# why not have a target $(SSHCONFIG) and let make do the job?
# the problem is the $(FAB) macro in the $(RUNSTAGE) macro, it uses $@ as the fab target
#
sshconfig: preflight autogenerated
	mkdir -pv $(shell dirname $(SSHCONFIG))
	test -f $(SSHCONFIG) || \
		( \
			SSHCONFIG=$(SSHCONFIG) $(RUNSTAGE); \
			find $(shell dirname $(SSHCONFIG))/.config.fragment.*.txt | sort -n | uniq | xargs -n1 --no-run-if-empty cat | tee $(SSHCONFIG); \
			find $(shell dirname $(SSHCONFIG))/.config.fragment.*.txt | xargs -n1 --no-run-if-empty rm; \
		)

clean:
	rm -rf ./$(shell basename $(TMPDIR))
	rm -rfv ./$(shell basename $(AUTOGENERATED))
	find . -type f -ipath '*.pyc' | xargs -n1 --no-run-if-empty -- rm -v

